apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
  - ../workload
  - ./configmap.yaml
images:
  - name: devlaunchers/cms-api
    newName: devlaunchers/cms-api
    newTag: f8032ad-202112201908 # {"$imagepolicy": "strapi:strapi:tag"}
# ACI yaml definition https://docs.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: strapi
    name: strapi
    labels:
      app: strapi
  spec:
    template:
      spec:
        containers:
        - name: strapi
          livenessProbe:
            $patch: delete
          resources:
            # Because of https://github.com/virtual-kubelet/azure-aci/issues/17
            # limits and requests have to be equal
            limits:
              cpu: 0.03
              memory: 0.2
            requests:
              cpu: 0.03
              memory: 0.2
        nodeSelector:
          type: virtual-kubelet
        tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule