apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
  - ../workload
  - ./configmap.yaml
images:
  - name: devlaunchers/cms-api
    newName: devlaunchers/cms-api
    newTag: 41e4f6f-202112042058 # {"$imagepolicy": "strapi:strapi:tag"}
